language: java
dist: trusty
withIntermediateDirectories: YES
jdk:
  - oraclejdk8
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mkdir -p /var/log/hot.const520.com
  - mvn test -B