site:
  host: http://localhost:8080
crawler:
  task:
    enable: false
    initialDelay: 60000
    fixedRate: 30000
    cron: "*/5 * * * * ?"
spring:
  cache:
    type: redis
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    ssl: false
    jedis:
      pool:
        max-active: 7
        max-idle: 7
        min-idle: 2
        max-wait: -1ms
