domain: https://hot.const520.com
crawler:
  task:
    enable: true
    threadPoolNum: 5
    initialDelay: 60000
    fixedRate: 60000
    cron: "*/5 * * * * ?"
#--------------------------------------------
spring:
  cache:
    type: redis
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    ssl: false
    jedis:
      pool:
        max-active: 7
        max-idle: 7
        min-idle: 2
        max-wait: -1ms
logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.taogen.hotcrawler: INFO
    org.hibernate: ERROR
  path: /var/log/hot.const520.com
  file: ${logging.path}/${spring.application.name}.log