domain: https://test.hot.const520.com
crawler:
  task:
    enable: false
    threadPoolNum: 5
    initialDelay: 60000
    fixedRate: 180000
    cron: "*/5 * * * * ?"
  chromeDriver:
    enable: true
    linuxPath: "/hotcrawler/chromedriver"
    winPath: "D:/chromedriver-75.exe"
#--------------------------------------------
spring:
  cache:
    type: redis
  redis:
    database: 1
    host: localhost
    port: 6379
    password:
    ssl: false
    jedis:
      pool:
        max-active: 7
        max-idle: 7
        min-idle: 2
        max-wait: -1ms
logging:
  level:
    root: error
    org.springframework.web: error
    com.taogen.hotcrawler: debug
    org.hibernate: error
server:
  address: test.hot.const520.com
  port: 8081