crawler:
  task:
    initialDelay: 60000
    fixedRate: 10000
    cron: "*/5 * * * * ?"
spring:
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        max-active: 7
        max-idle: 7
        min-idle: 2
        max-wait: -1ms